detection_site/detection_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('object_detection/', include('object_detection.urls')),
    path('', RedirectView.as_view(url='/object_detection/', permanent=True)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

detection_site/object_detection/urls.py
from django.urls import path

from .views import home, register, user_login, user_logout, dashboard, process_image_feed, add_image_feed, delete_image

from django.conf import settings
from django.conf.urls.static import static
app_name = 'object_detection'

urlpatterns = [
    path('', home, name='home'),
    path('register/', register, name='register'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('dashboard/', dashboard, name='dashboard'),
    path('process/<int:feed_id>/', process_image_feed, name='process_feed'),
    path('add-image-feed/', add_image_feed, name='add_image_feed'),
    path('image/delete/<int:image_id>/', delete_image, name='delete_image'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

detection_site/object_detection/models.py
from django.db import models
from django.conf import settings

class ImageFeed(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/')
    processed_image = models.ImageField(upload_to='processed_images/', null=True, blank=True)

    def __str__(self):
        return f"{self.user.username} - {self.image.name}"

class DetectedObject(models.Model):
    image_feed = models.ForeignKey(ImageFeed, related_name='detected_objects', on_delete=models.CASCADE)
    object_type = models.CharField(max_length=100)
    confidence = models.FloatField()
    location = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.object_type} ({self.confidence * 100}%) on {self.image_feed.image.name}"


detection_site/object_detection/forms.py
from django import forms
from .models import ImageFeed


class ImageFeedForm(forms.ModelForm):
    class Meta:
        model = ImageFeed
        fields = ['image']
        widgets = {
            'image': forms.FileInput(attrs={'accept': 'image/*'}),
        }
        help_texts = {
            'image': 'Загрузите изображение.',
        }

detection_site/object_detection/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.decorators import login_required
from .models import ImageFeed
from .utils import process_image
from .forms import ImageFeedForm


def home(request):
    return render(request, 'object_detection/home.html')


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('object_detection:dashboard')
    else:
        form = UserCreationForm()
    return render(request, 'object_detection/register.html', {'form': form})


def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('object_detection:dashboard')
    else:
        form = AuthenticationForm()
    return render(request, 'object_detection/login.html', {'form': form})


@login_required
def user_logout(request):
    logout(request)
    return redirect('object_detection:login')


@login_required
def dashboard(request):
    image_feeds = ImageFeed.objects.filter(user=request.user)
    return render(request, 'object_detection/dashboard.html', {'image_feeds': image_feeds})


@login_required
def process_image_feed(request, feed_id):
    image_feed = get_object_or_404(ImageFeed, id=feed_id, user=request.user)
    process_image(feed_id)  # Consider handling this asynchronously
    return redirect('object_detection:dashboard')


@login_required
def add_image_feed(request):
    if request.method == 'POST':
        form = ImageFeedForm(request.POST, request.FILES)
        if form.is_valid():
            image_feed = form.save(commit=False)
            image_feed.user = request.user
            image_feed.save()
            return redirect('object_detection:dashboard')
    else:
        form = ImageFeedForm()
    return render(request, 'object_detection/add_image_feed.html', {'form': form})

@login_required
def delete_image(request, image_id):
    image = get_object_or_404(ImageFeed, id=image_id, user=request.user)  # Ensuring only the owner can delete
    image.delete()
    return redirect('object_detection:dashboard')

detection_site/object_detection/templates/object_detection/add_image_feed.html
{% extends "object_detection/base.html" %}

{% block content %}
<h2>Добавление изображения</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" style="border-radius: 5px; border: none; background-color: #007bff; color: white; padding: 5px 5px 5px 5px;">Загрузить изображение</button>
</form>
{% endblock %}

detection_site/object_detection/templates/object_detection/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}Face Detection Platform{% endblock %}</title>
    <!-- Include Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet">

</head>
<body style="background-color: #e2e2e2; font-family: 'Ubuntu', sans-serif;">
    <header>
        <!-- Bootstrap Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'object_detection:home' %}">Object Detection Platform</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'object_detection:home' %}">Главная</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'object_detection:dashboard' %}">Дэшборд</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'object_detection:logout' %}">Выход</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'object_detection:login' %}">Вход</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'object_detection:register' %}">Регистрация</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    <main class="container mt-4">
        {% block content %}{% endblock %}
    </main>
    <!-- Bootstrap and other dependencies should be loaded right before the closing body tag -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

detection_site/object_detection/templates/object_detection/dashboard.html
{% extends "object_detection/base.html" %}

{% block content %}
<h2>Дэшборд</h2>
<a href="{% url 'object_detection:add_image_feed' %}" class="btn btn-primary mb-3">Добавить изображение</a>

{% for feed in image_feeds %}
<div class="card mb-3">
    <div class="card-header">
        <a href="{% url 'object_detection:process_feed' feed.id %}" class="btn btn-secondary">Проверить изображение</a>
    </div>
    <div class="card-body">
        <a href="{{ feed.image.url }}" target="_blank">
            <img src="{{ feed.image.url }}" alt="Original Image" style="width: 50px; height: 50px;">
        </a>
        {% if feed.processed_image %}
        <a href="{{ feed.processed_image.url }}" target="_blank">
            <img src="{{ feed.processed_image.url }}" alt="Processed Image" style="width: 50px; height: 50px;">
        </a>
        <ul>
            {% for obj in feed.detected_objects.all %}
            <li>{{ obj.object_type }} - {{ obj.confidence|floatformat:2 }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
    <form action="{% url 'object_detection:delete_image' feed.id %}" method="post">
        {% csrf_token %}
        <button type="submit" style="border-radius: 5px; border: none; background-color: rgb(218, 123, 123); margin: 10px 0px 10px 10px; color: white;">Удалить</button>
    </form>
</div>
{% endfor %}
{% endblock %}

detection_site/object_detection/templates/object_detection/home.html
{% extends "object_detection/base.html" %}

{% block content %}
<p>Добро пожаловать в Object Detection Platform, где мы раскрываем потенциал компьютерного зрения для преобразования отраслей.</p>
<h3>Что такое компьютерное зрение?</h3>
<p>Компьютерное зрение — это область искусственного интеллекта, которая позволяет машинам видеть, понимать и реагировать на окружающую среду. У него множество применений, включая обнаружение объектов, классификацию изображений, распознавание лиц и сегментацию изображений.</p>
<h3>Наш Опыт</h3>
<p>Мы разрабатываем индивидуальные решения для компьютерного зрения с использованием глубокого обучения, OpenCV и других методов.</p>
<h3>Начало работы</h3>
<p>Перейдите на страницу <a href="{% url 'object_detection:dashboard' %}">Дэшборд</a> для того чтобы опробовать наше приложение</p>
{% endblock %}

detection_site/object_detection/templates/object_detection/login.html
{% extends "object_detection/base.html" %}

{% block content %}
<h2>Вход</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" style="border-radius: 5px; border: none; background-color: #007bff; color: white; padding: 1px 5px 1px 5px; margin: 0 0 10px 0; width: 70px;">Вход</button>
</form>
<a href="{% url 'object_detection:register' %}" style="border-radius: 5px; border: none; background-color: #898c8f; color: white; padding: 5px 5px 5px 5px; font-size: 14px;">Регистрация</a>
{% endblock %}

detection_site/object_detection/templates/object_detection/register.html
{% extends "object_detection/base.html" %}

{% block content %}
<h2>Регистрация</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" style="border-radius: 5px; border: none; background-color: #007bff; color: white; padding: 1px 5px 1px 5px; margin: 0 0 10px 0; height: 30px;">Регистрация</button>
</form>
<a href="{% url 'object_detection:login' %}" style="border-radius: 5px; border: none; background-color: #898c8f; color: white; padding: 5px 5px 5px 5px; font-size: 14px;">Вход</a>
{% endblock %}